#! /bin/bash
#This script has been used to populate both /x/wmn21/elliottml/GraphTheoryAnalyses/data/nbackROIrawLocal and /x/wmn21/elliottml/GraphTheoryAnalyses/data/nBackROI, nBackROI local is preferred because it should not have any empty files. The files created are the activity data for the 116 ROIS for each of the 0back and 2back

subDir=/x/ltm7/PETBANKS/spm5.pet.prep_raced.v2_NEW.1st.level/
cd $subDir
subs=$(ls -d R*)
mask=/x/wmn21/elliottml/GraphTheoryAnalyses/PET_MNI_N27_EZ_ML.nii
LOG=/x/wmn21/elliottml/GraphTheoryAnalyses/Log.getPETData
date >> Log.PETData

for sub in $subs;do
    DIRECTORY=${subDir}/$sub
    if [ "$(ls -A $DIRECTORY)" ]; then
	touch /x/wmn21/elliottml/GraphTheoryAnalyses/data/nbackROIrawLocal/rawData_082714_${sub}_0bk.txt
	outPutFile0bk=/x/wmn21/elliottml/GraphTheoryAnalyses/data/nbackROIrawLocal/rawData_082714_${sub}_0bk.txt
	3dROIstats -mask $mask -quiet /x/wmn21/elliottml/GraphTheoryAnalyses/data/rawData/swMSrBFZ${sub}_0bk[1-7]*.hdr >> $outPutFile0bk
	touch /x/wmn21/elliottml/GraphTheoryAnalyses/data/nbackROIrawLocal/rawData_082714_${sub}_2bk.txt
	outPutFile2bk=/x/wmn21/elliottml/GraphTheoryAnalyses/data/nbackROIrawLocal/rawData_082714_${sub}_2bk.txt
	3dROIstats -mask $mask -quiet /x/wmn21/elliottml/GraphTheoryAnalyses/data/rawData/swMSrBFZ${sub}_2bk[1-7]*.hdr >> $outPutFile2bk
    else
	echo "$DIRECTORY is empty!"
    fi
    
done
